apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-01
  lables:
    type: local
spec:
  capacity:
    storage:5Gi
  accessModes:
    - ReadWriteOnce
  hostpath:
    path: /home/prabhu/k8/volume
 ---
 apiVersion:  v1
 kind: PersistentVolume
 metadata:
  name: pv-02
  lables:
    type: local
 spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostpath: /home/prabhu/k8/volume
