apiVersion: v1
kind: Secret
metadata:
 name: mysecret
type: Opaque
date: 
 username: cHJhYmh1   #to get username " echo -n 'prabhu' | base64
 password: cHJhYmh1MTIz   #to get username " echo -n 'prabhu123' | base64
    
